// Code generated by hertz generator.

package main

import (
	"shield/gateway/biz/config"
	"shield/gateway/biz/middleware"
	"shield/gateway/biz/repos"
	"shield/gateway/biz/rpc"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	config.Init()
	rpc.Init()
	repos.Init()

	h := server.Default()

	h.Use(middleware.Suite()...)

	register(h)
	h.Spin()
}
