// Code generated by hertz generator.

package main

import (
	handler "shield/gateway/biz/handler"
	"shield/gateway/biz/router/index"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	
	r.GET("/login", index.Login)
	r.GET("/error/:error_code", index.Error)

	idx := r.Group("/index", index.IndexMw()...)
	{
		idx.GET("/home", index.Home)
	}
}
