// Code generated by hertz generator.

package gateway

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createaccountMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		func(c context.Context, ctx *app.RequestContext) {
			ctx.Next(c)
		},
	}
}

func _queryloginrecordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logoutMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resetpasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _switchaccountstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatepasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryaccountMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _operatorMw() []app.HandlerFunc {
	// your code...
	return nil
}
