// Code generated by hertz generator.

package gateway

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	gateway "shield/gateway/biz/model/kaidog/shield/gateway"
)

// Login .
// @router /login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req gateway.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(gateway.BaseResp)

	c.JSON(consts.StatusOK, resp)
}

// Logout .
// @router /logout [POST]
func Logout(ctx context.Context, c *app.RequestContext) {
	var err error
	var req gateway.LogoutReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(gateway.BaseResp)

	c.JSON(consts.StatusOK, resp)
}

// QueryUserInfo .
// @router /user_info [GET]
func QueryUserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req gateway.UserInfoQueryReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(gateway.BaseResp)

	c.JSON(consts.StatusOK, resp)
}

// QueryLoginRecord .
// @router /login_record [GET]
func QueryLoginRecord(ctx context.Context, c *app.RequestContext) {
	var err error
	var req gateway.LoginRecordQueryReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(gateway.BaseResp)

	c.JSON(consts.StatusOK, resp)
}

// UpdatePassword .
// @router update_password [POST]
func UpdatePassword(ctx context.Context, c *app.RequestContext) {
	var err error
	var req gateway.PasswordUpdateReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(gateway.BaseResp)

	c.JSON(consts.StatusOK, resp)
}
